version: '3.2'
services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: debug
    ports:
      - "30001:30001"
    volumes:
      - ./tmp/output:/output
      - ./src/test/resources/json:/root/src/test/resources/json
  server2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: debug
    ports:
      - "30002:30001"
    volumes:
      - ./tmp/output:/output
      - ./src/test/resources/json:/root/src/test/resources/json
